# Generated by Django 4.0.4 on 2022-06-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acp', '0004_alter_partition_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partition',
            options={'ordering': ['name']},
        ),
    ]
