# Generated by Django 4.0.4 on 2022-07-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acp', '0006_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='small_nodes_list',
            new_name='nodes',
        ),
    ]
