# Generated by Django 4.0.4 on 2022-07-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acp', '0009_alter_job_options_alter_job_calc_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['jobid']},
        ),
    ]
