# Generated by Django 4.0.5 on 2022-07-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acp', '0010_alter_job_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=20, unique=True)),
                ('partition', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('cpus', models.IntegerField()),
                ('cpus_status', models.CharField(max_length=100)),
                ('memory', models.IntegerField()),
                ('tmp', models.IntegerField()),
            ],
            options={
                'ordering': ['node'],
            },
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-job_condition', 'jobid']},
        ),
    ]
