# Generated by Django 4.0.5 on 2022-07-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acp', '0011_node_alter_job_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobid',
            field=models.CharField(max_length=20),
        ),
    ]
